### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by jorinvo** [jorinvo/me#3]
There is a default rendering for that but I should check if it looks nice..

**Comment by anko** [comment]
Do you still have an RSS feed? I clicked what I thought was an RSS icon (![RSS icon?](https://cloud.githubusercontent.com/assets/5231746/12594772/0fba7268-c478-11e5-9eb0-e87182c86a38.png)) in the top bar on an article but it just seems to link to the same article.

**Comment by jorinvo** [comment]
Hi @anko! Thanks for stopping by and letting me know!
I only tested the RSS feed on the front page where it is working. But as I saw now it doesn't work on the sub pages.
I found this [issues](https://github.com/spf13/hugo/issues/532) (I'm using Hugo) and I [updated](https://github.com/jorinvo/home/commit/8e71facb62703e2207fd23d05020bd2fd9f8a743) the blog.
Feel free to try the [feed](https://jorin.me/index.xml) again.

**Comment by anko** [comment]
Great, works now!
